frr defaults traditional
hostname agg01
service integrated-vtysh-config
!
interface eth1
 ip address 10.255.0.1/31
 ip ospf area 0
!
interface eth2
 description ACCESS11-VLAN110
interface eth3
 description ACCESS12-VLAN120
interface eth4
 description ACCESS13-VLAN130
!
interface lo
 ip address 10.255.255.21/32
!
router ospf
 ospf router-id 10.255.255.21
 network 10.255.255.21/32 area 0
!

